config/routes.rb
Rails.application.routes.draw do
  root 'pdfs#index'
  resources :pdfs

end

app/models/pdf.rb
class Pdf < ActiveRecord::Base
  mount_uploader :template, TemplateUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pdfs_controller.rb
class PdfsController < ApplicationController

  def index
    @pdf = Pdf.last
  end

  def new
    @pdf = Pdf.new
  end

  def create
    @pdf = Pdf.new(pdf_params)
    PdfMaker.create(params[:pdf][:name])
    @pdf.template = Rails.root.join('tmp/stamp_pages.pdf').open
    if @pdf.save
      redirect_to root_path
    end
  end

  private

  def pdf_params
    params.require(:pdf).permit(:name,:template)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_helper.rb
module PdfHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PdflibApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdfs/index.html.slim
h1 Pdfs#index
p Find me in app/views/pdf/index.html.slim

.image
  = image_tag "test.pdf"
  = image_tag @pdf.template_url

.links
  = link_to "New", new_pdf_path

app/views/pdfs/new.html.slim
h1 New PDF

.thing
  = simple_form_for @pdf, :html => {:multipart => true} do |f|
    = f.label :name
    = f.text_field :name
    = f.label :template
    = f.file_field :template
    = f.submit "hey"

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>